

namespace SeleniumTests.Enums
{
	public enum BaseChoiceType
	{
		INT,
		DOUBLE,
		BOOL,
		EMAIL
	}

	public enum EntityType
	{
		TRADING_POST_LISTING_ENTITY,
		TRADING_POST_CATEGORY_ENTITY,
		FARM_ENTITY,
		MILK_TEST_ENTITY,
		IMPORTANT_DOCUMENT_CATEGORY_ENTITY,
		TECHNICAL_DOCUMENT_CATEGORY_ENTITY,
		QUALITY_DOCUMENT_CATEGORY_ENTITY,
		QUALITY_DOCUMENT_ENTITY,
		TECHNICAL_DOCUMENT_ENTITY,
		IMPORTANT_DOCUMENT_ENTITY,
		NEWS_ARTICLE_ENTITY,
		AGRI_SUPPLY_DOCUMENT_CATEGORY_ENTITY,
		SUSTAINABILITY_POST_ENTITY,
		AGRI_SUPPLY_DOCUMENT_ENTITY,
		PROMOTED_ARTICLES_ENTITY,
	}
}